"""Self-host the Google Fonts the dashboard uses.

What this does:
1. Fetches the Google Fonts CSS with a modern UA so we get woff2 sources.
2. Downloads every woff2 file referenced into /fonts/.
3. Rewrites the @font-face src() URLs to point to the local /fonts/ copies.
4. Writes /fonts.css with the rewritten declarations.

After running once, swap the <link href="https://fonts.googleapis.com/..."> in
index.html and viewer.html for <link href="fonts.css">. Local hosting:
  - eliminates the 2x DNS+TLS roundtrip to fonts.googleapis.com + fonts.gstatic.com
  - removes the privacy leak (Google sees every page-load when CDN-hosted)
  - lets us preload the critical font files (further CLS reduction)
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Same family/weight set the dashboard currently uses.
GFONTS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Inter:wght@400;500;600;700;800;900"
    "&family=Amiri:wght@400;700"
    "&family=Tajawal:wght@400;500;700;800"
    "&family=Cairo:wght@500;700;900"
    "&family=JetBrains+Mono:wght@400;500"
    "&display=swap"
)

# Modern UA -> Google returns woff2 (the lightest format).
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

ROOT = Path(__file__).parent
FONTS_DIR = ROOT / "fonts"


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def main() -> None:
    FONTS_DIR.mkdir(exist_ok=True)
    print(f"fetching Google Fonts CSS…")
    css = fetch(GFONTS_URL).decode("utf-8")
    # Find every url(https://fonts.gstatic.com/...woff2)
    woff2_urls = sorted(set(re.findall(r"url\((https://fonts\.gstatic\.com[^)]+\.woff2)\)", css)))
    print(f"  found {len(woff2_urls)} woff2 files")

    # Map: remote URL -> local filename + relative path
    mapping: dict[str, str] = {}
    for url in woff2_urls:
        # Filename: keep something readable. Last 2 path segments + hash.
        # e.g. https://fonts.gstatic.com/s/inter/v18/UcCx-RH7sCnsxVcydH...woff2
        parts = url.rsplit("/", 3)[-3:]  # [family]/[version]/[hash.woff2]
        family = parts[0]
        hash_name = parts[-1]
        # Try to detect weight + subset from the surrounding CSS comment to make
        # filenames human-readable: Google emits e.g. "/* arabic */" right before
        # the @font-face block, and font-weight is inside the block.
        local_name = f"{family}-{hash_name}"
        local_path = FONTS_DIR / local_name
        if not local_path.exists():
            print(f"  ↓ {local_name}")
            data = fetch(url)
            local_path.write_bytes(data)
        mapping[url] = f"fonts/{local_name}"

    # Rewrite the CSS to point at local files
    rewritten = css
    for remote, local in mapping.items():
        rewritten = rewritten.replace(remote, local)

    # CLS optimisation: switch display fonts (Amiri, Cairo) to font-display: optional
    # so the page never reflows when they swap in late. Body fonts keep `swap` because
    # users need them to actually appear.
    blocks = re.split(r"(@font-face \{[^}]*\})", rewritten)
    for i, b in enumerate(blocks):
        if b.startswith("@font-face"):
            m = re.search(r"font-family:\s*'([^']+)'", b)
            if m and m.group(1) in ("Amiri", "Cairo"):
                blocks[i] = b.replace("font-display: swap;", "font-display: optional;")
    rewritten = "".join(blocks)

    out_path = ROOT / "fonts.css"
    header = (
        "/* Self-hosted Google Fonts for Juthoor.\n"
        " * Generated by _build_fonts.py — do not edit by hand.\n"
        " * Re-run when font weights or families change in index.html.\n"
        " * Amiri + Cairo use font-display: optional (CLS optimisation);\n"
        " * other families use font-display: swap. */\n\n"
    )
    out_path.write_text(header + rewritten, encoding="utf-8")
    total_kb = sum(p.stat().st_size for p in FONTS_DIR.glob("*.woff2")) / 1024
    print(f"\n  fonts.css written, {len(mapping)} files, {total_kb:.1f} KB total in /fonts/")


if __name__ == "__main__":
    main()
