"""Audit Layer 2 v2 records for missing/partial fields.

Codex audit (2026-05-19) flagged 302 records whose `binary_reading_en` and
`binary_reading_ar` are blank. The verdict (mode) is still recorded, but the
reading-level evidence is missing — so any downstream rendering shows the
mode without showing why.

This script:
  1. Counts and groups the partial records by mode + L3 letter.
  2. Writes a human-readable audit at outputs/audits/layer_2_partial_records.md
  3. Stamps the per-record JSONL with a `needs_binary_reading` boolean so
     downstream consumers can filter on it programmatically.

Run: python scripts/layer_2/audit_partial_records.py
"""

from __future__ import annotations

import json
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parents[2]
RESULTS = ROOT / "computational" / "data" / "layer_2_results_v2.jsonl"
REPORT = ROOT / "computational" / "layer-2-partial-records.md"


def main() -> int:
    if not RESULTS.exists():
        print(f"ERROR: {RESULTS} not found", file=sys.stderr)
        return 1

    records = []
    partial_count = 0
    by_mode: Counter[str] = Counter()
    by_letter: Counter[str] = Counter()
    samples_by_mode: dict[str, list[str]] = defaultdict(list)

    for line in RESULTS.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        en = (r.get("binary_reading_en") or "").strip()
        ar = (r.get("binary_reading_ar") or "").strip()
        is_partial = not en or not ar
        r["needs_binary_reading"] = is_partial
        records.append(r)
        if is_partial:
            partial_count += 1
            by_mode[r.get("mode", "?")] += 1
            by_letter[r.get("third", "?")] += 1
            if len(samples_by_mode[r.get("mode", "?")]) < 5:
                samples_by_mode[r["mode"]].append(r.get("tri_root", "?"))

    # Atomic rewrite of the JSONL with the new flag stamped in.
    tmp = RESULTS.with_suffix(RESULTS.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
        f.flush()
        os.fsync(f.fileno())
    tmp.replace(RESULTS)

    total = len(records)
    pct = (partial_count / total * 100) if total else 0.0
    lines = [
        "# Layer 2 v2 — partial-record audit",
        "",
        "Records where `binary_reading_en` or `binary_reading_ar` is blank.",
        "The verdict (mode) is still recorded; the reading-level evidence is missing.",
        "",
        f"_Generated by `scripts/layer_2/audit_partial_records.py`. Re-run after each batch._",
        "",
        f"## Summary",
        "",
        f"- **Total records:** {total:,}",
        f"- **Partial records:** {partial_count:,}  ({pct:.1f}%)",
        f"- **Fully populated:** {total - partial_count:,}",
        "",
        "## Distribution by mode",
        "",
        "| Mode | Partial count | % of partial |",
        "|------|--------------:|-------------:|",
    ]
    for mode, count in by_mode.most_common():
        share = (count / partial_count * 100) if partial_count else 0
        lines.append(f"| {mode} | {count} | {share:.1f}% |")

    lines += [
        "",
        "## Distribution by third-letter (L3)",
        "",
        "| L3 | Partial count |",
        "|----|--------------:|",
    ]
    for letter, count in by_letter.most_common(15):
        lines.append(f"| {letter} | {count} |")

    lines += ["", "## Sample partial roots, by mode", ""]
    for mode, samples in sorted(samples_by_mode.items()):
        lines.append(f"- **{mode}**: {', '.join(samples)}")

    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  audited {total} records: {partial_count} partial ({pct:.1f}%)")
    print(f"  flagged needs_binary_reading on each, in-place")
    print(f"  wrote {REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
