#!/usr/bin/env python3
"""Build the Arabic <-> Hebrew cognate dataset (the close-sister seam).
These are well-established Semitic cognates — verifiable, not from-memory reaching.
PERFECT = same root, no shift; STRONG = one regular Semitic shift (ث↔š, ض↔ts/ṣ, ذ↔z, خ↔ḥ, ظ↔ts)."""
import json, sys
from collections import Counter
sys.stdout.reconfigure(encoding='utf-8')
ROOT='C:/Users/yassi/AI Projects/The Arabic Tongue (nature-genome-application)/'

# [arabic, hebrew, gloss, verdict, category]
E=[
# Body
('عَين','עַיִן ʿayin','eye, spring','PERFECT','body'),
('أُذُن','אֹזֶן ʾozen','ear','PERFECT','body'),
('يَد','יָד yad','hand','PERFECT','body'),
('رِجل','רֶגֶל regel','foot, leg','PERFECT','body'),
('كَتِف','כָּתֵף katef','shoulder','PERFECT','body'),
('عَظم','עֶצֶם ʿetsem','bone — ظ↔ts','STRONG','body'),
('كَبِد','כָּבֵד kaved','liver','PERFECT','body'),
('قَلب','לֵב lev','heart — the l-b core','STRONG','body'),
('رَأس','רֹאשׁ rosh','head','PERFECT','body'),
('بَطن','בֶּטֶן beten','belly, womb','PERFECT','body'),
('لِسان','לָשׁוֹן lashon','tongue, language','PERFECT','body'),
('سِنّ','שֵׁן shen','tooth — ש↔س','STRONG','body'),
('شَعر','שֵׂעָר seʿar','hair — ש↔ش','STRONG','body'),
('أَنف','אַף ʾaf','nose (n assimilated)','STRONG','body'),
('فَم','פֶּה peh','mouth','STRONG','body'),
('دَم','דָּם dam','blood','PERFECT','body'),
('إِصبَع','אֶצְבַּע ʾetsbaʿ','finger','PERFECT','body'),
('قَرن','קֶרֶן qeren','horn','PERFECT','body'),
('جِلد','גֶּלֶד geled','skin, scab','PERFECT','body'),
('رُكبة','בֶּרֶךְ berekh','knee — metathesis r-k-b↔b-r-k','STRONG','body'),
('لَحم','לֶחֶם leḥem','flesh / Heb. bread (same b-flesh root)','STRONG','body'),
('نَفس','נֶפֶשׁ nefesh','soul, self, breath','PERFECT','body'),
('روح','רוּחַ ruaḥ','spirit, wind, breath','PERFECT','body'),
# Kinship & person
('أَب','אָב ʾav','father','PERFECT','kin'),
('أُمّ','אֵם ʾem','mother','PERFECT','kin'),
('ابن','בֵּן ben','son','PERFECT','kin'),
('بِنت','בַּת bat','daughter','PERFECT','kin'),
('أَخ','אָח ʾaḥ','brother','PERFECT','kin'),
('أُخت','אָחוֹת ʾaḥot','sister','PERFECT','kin'),
('حَمّ','חָם ḥam','father-in-law','PERFECT','kin'),
('عَمّ','עַם ʿam','kinsfolk, people','PERFECT','kin'),
('يَتيم','יָתוֹם yatom','orphan','PERFECT','kin'),
('أَرمَلة','אַלְמָנָה ʾalmanah','widow','PERFECT','kin'),
('أَنا','אֲנִי ʾani','I','PROTO-FAMILY','pronoun'),
('أَنتَ','אַתָּה ʾatah','you (m.)','PROTO-FAMILY','pronoun'),
('نَحنُ','אֲנַחְנוּ ʾanaḥnu','we','PROTO-FAMILY','pronoun'),
('هُو','הוּא huʾ','he','PERFECT','pronoun'),
('هي','הִיא hiʾ','she','PERFECT','pronoun'),
('مَن','מִי mi','who','STRONG','pronoun'),
('ما','מָה mah','what','PERFECT','pronoun'),
('مِن','מִן min','from','PROTO-FAMILY','prep'),
('عَلى','עַל ʿal','on, upon','PERFECT','prep'),
('تَحت','תַּחַת taḥat','under','PERFECT','prep'),
('بَين','בֵּין bein','between','PERFECT','prep'),
('كُلّ','כֹּל kol','all, every','PERFECT','prep'),
# Nature
('ماء','מַיִם mayim','water','PERFECT','nature'),
('نَهر','נָהָר nahar','river','PERFECT','nature'),
('يَمّ','יָם yam','sea','PERFECT','nature'),
('سَماء','שָׁמַיִם shamayim','sky, heaven','PERFECT','nature'),
('أَرض','אֶרֶץ ʾerets','earth, land — ض↔ts','STRONG','nature'),
('شَمس','שֶׁמֶשׁ shemesh','sun','STRONG','nature'),
('لَيل','לַיְלָה laylah','night','PERFECT','time'),
('يَوم','יוֹם yom','day','PERFECT','time'),
('كَوكَب','כּוֹכָב kokhav','star','PERFECT','nature'),
('نار/نَير','נֵר ner','fire / lamp','STRONG','nature'),
('نور','אוֹר ʾor','light','STRONG','nature'),
('ظِلّ','צֵל tsel','shadow — ظ↔ts','STRONG','nature'),
('صَخر','צוּר tsur','rock — ص↔ts','STRONG','nature'),
('جَبَل','גְּבוּל gevul','mountain / border','STRONG','nature'),
('رَمل? حَجَر','אֶבֶן ʾeven','stone (parallel)','PROVISIONAL','nature'),
('وَرد','וֶרֶד vered','rose','PERFECT','nature'),
('زَيت','זַיִת zayit','olive, oil','PERFECT','nature'),
('عِنَب','עֵנָב ʿenav','grape','PERFECT','nature'),
('تين','תְּאֵנָה teʾenah','fig','STRONG','nature'),
('شَعير','שְׂעוֹרָה seʿorah','barley — ش↔ש','STRONG','nature'),
('لَبَن','לָבָן lavan','milk / Heb. white (milk=white)','PERFECT','nature'),
('حَليب','חָלָב ḥalav','milk','PERFECT','nature'),
('عَسَل','עָסִיס ʿasis','honey / sweet-juice','STRONG','nature'),
('مِلح','מֶלַח melaḥ','salt','PERFECT','nature'),
('ذَهَب','זָהָב zahav','gold — ذ↔z','STRONG','nature'),
('نُحاس','נְחֹשֶׁת neḥoshet','copper, bronze','STRONG','nature'),
# Numbers
('واحِد','אֶחָד ʾeḥad','one','STRONG','num'),
('اثنان','שְׁנַיִם shnayim','two — ث↔š','STRONG','num'),
('ثَلاث','שָׁלוֹשׁ shalosh','three — ث↔š','STRONG','num'),
('أَربَع','אַרְבַּע ʾarbaʿ','four','PERFECT','num'),
('خَمس','חָמֵשׁ ḥamesh','five — خ↔ḥ, س↔š','STRONG','num'),
('سِتّ','שֵׁשׁ shesh','six','STRONG','num'),
('سَبع','שֶׁבַע shevaʿ','seven','PERFECT','num'),
('ثَمان','שְׁמֹנֶה shmoneh','eight — ث↔š','STRONG','num'),
('تِسع','תֵּשַׁע teshaʿ','nine','PERFECT','num'),
('عَشر','עֶשֶׂר ʿeser','ten','PERFECT','num'),
('مِئة','מֵאָה meʾah','hundred','PERFECT','num'),
('أَلف','אֶלֶף ʾelef','thousand','PERFECT','num'),
# Verbs — perception/mind/speech
('كَتَب','כָּתַב katav','to write','PERFECT','action'),
('قَرَأ','קָרָא qaraʾ','to read, call out','PERFECT','action'),
('سَمِع','שָׁמַע shamaʿ','to hear — س↔š','STRONG','mind'),
('رَأى','רָאָה raʾah','to see','PERFECT','mind'),
('عَرَف/يَدَع','יָדַע yadaʿ','to know (parallel)','PROVISIONAL','mind'),
('ذَكَر','זָכַר zakhar','to remember — ذ↔z','STRONG','mind'),
('حَكَم','חָכַם ḥakham','to be wise','PERFECT','mind'),
('سَأَل','שָׁאַל shaʾal','to ask — س↔š','STRONG','mind'),
('أَمَر','אָמַר ʾamar','to say, command','PERFECT','abstract'),
('دَبَّر','דָּבָר davar','word, thing, to speak','PERFECT','abstract'),
('صَرَخ','צָרַח tsaraḥ','to cry out — ص↔ts','STRONG','abstract'),
('بَكى','בָּכָה bakhah','to weep','PERFECT','abstract'),
('ضَحِك','צָחַק tsaḥaq','to laugh — ض↔ts','STRONG','abstract'),
# Verbs — action/state
('أَكَل','אָכַל ʾakhal','to eat','PERFECT','action'),
('ماتَ','מֵת met','to die','PERFECT','kin'),
('قَتَل','קָטַל qatal','to kill','PERFECT','action'),
('وَلَد','יָלַד yalad','to give birth — و↔י','STRONG','kin'),
('بَنى','בָּנָה banah','to build','PERFECT','action'),
('سَكَن','שָׁכַן shakhan','to dwell — س↔š','STRONG','motion'),
('عَمَد','עָמַד ʿamad','to stand (Ar. pillar/uphold)','PERFECT','motion'),
('وَسَن','יָשֵׁן yashen','to sleep — و↔י','STRONG','motion'),
('عَبَد','עָבַד ʿavad','to work, serve, worship','PERFECT','action'),
('مَلَك','מָלַךְ malakh','to reign','PERFECT','abstract'),
# Sacred / abstract
('مَلِك','מֶלֶךְ melekh','king','PERFECT','abstract'),
('كاهِن','כֹּהֵן kohen','priest','PERFECT','abstract'),
('نَبيّ','נָבִיא naviʾ','prophet','PERFECT','abstract'),
('سِفر/سَفَر','סֵפֶר sefer','book, scroll','PERFECT','abstract'),
('بَرَكة','בְּרָכָה berakhah','blessing','PERFECT','abstract'),
('سَجَد','סָגַד sagad','to prostrate, worship','PERFECT','abstract'),
('قُدُس','קָדוֹשׁ qadosh','holy — س↔š','STRONG','abstract'),
('سَلام','שָׁלוֹם shalom','peace, wholeness — س↔š','STRONG','abstract'),
('خَطِئ','חָטָא ḥataʾ','to sin — خ↔ḥ','STRONG','abstract'),
('رَحِم','רַחַם raḥam','to be merciful','PERFECT','abstract'),
('حَنّ','חָנַן ḥanan','to be gracious','PERFECT','abstract'),
('ذَبَح','זָבַח zavaḥ','to sacrifice — ذ↔z','STRONG','abstract'),
('نَذَر','נָדַר nadar','to vow','PERFECT','abstract'),
('كَفَر','כָּפַר kafar','to atone, cover','PERFECT','abstract'),
('كَذَب','כָּזָב kazav','lie — ذ↔z','STRONG','abstract'),
('صَدَق','צָדַק tsadaq','to be true, righteous — ص↔ts','STRONG','abstract'),
('إله','אֱלוֹהַּ ʾeloah','god','PERFECT','abstract'),
('رَبّ','רַב rav','lord, master, great','PERFECT','abstract'),
]
entries=[]
for i,(ar,he,gl,v,cat) in enumerate(E, start=1):
    entries.append({'id':i,'arabic':ar,'hebrew':he,'gloss':gl,'verdict':v,'category':cat})
dist=Counter(e['verdict'] for e in entries)
out={'project':'The Arabic Tongue · Tier-A Semitic-sister cognates · Arabic ↔ Hebrew',
     'version':'2026-05-24','count':len(entries),
     'verdict_distribution':dict(dist.most_common()),
     'license':'CC-BY 4.0',
     'source_doc':'04-cross-linguistic/tier-a-hebrew-cognates.md',
     'note':'Well-established Semitic cognates. PERFECT=same root no shift; STRONG=one regular consonant shift (ث↔š, ض↔ts, ذ↔z, خ↔ḥ, ظ↔ts, س↔š).',
     'entries':entries}
json.dump(out,open(ROOT+'04-cross-linguistic/data/hebrew-cognates.json','w',encoding='utf-8'),ensure_ascii=False,indent=2)
top=dist['PERFECT']+dist['PROTO-FAMILY']+dist['STRONG']
print('Hebrew dataset: %d entries' % len(entries))
print('Distribution:', dict(dist.most_common()))
print('Top-tier (PERFECT+PROTO+STRONG): %d/%d = %d%%' % (top,len(entries),round(top/len(entries)*100)))
